"""The digit templates, and the nearest-template classifier that reads one glyph.

**Ten mean glyphs and a normalized cross-correlation. That is the whole classifier**, and it is
enough because the problem is much narrower than OCR: Brawl Stars draws HP in one fixed font at
one fixed size, the capture is aspect-normalized (`capture.normalized_aspect`), and the camera is
near-orthographic -- so a digit is 15-17 px tall wherever on screen it appears. There is
effectively one writer. A trained classifier is the obvious next step if this stops being enough,
and `scripts/vision_hp_calibrate.py` already emits the labelled glyph bank one would need; see
`read.py` for what would actually be gained.

**The templates are a MEASUREMENT, not a setting.** They live in `data/digits.npz` beside this
file and are regenerated by the calibration script, never hand-edited -- the same treatment
`brawl_vision/data/` gives the homography, and the same reason `weights.py` keeps the detector
blob next to the code that loads it rather than in a shared folder. What ships is small (10
glyphs, ~3 KB) and ours, so unlike the detector weights it is committed rather than fetched.

**How the shipped set was built, because "I drew some digits" would be a different artifact.**
1184 glyphs were harvested from `day10_gameplay.mp4` by running the detector, taking the white
connected components inside each box, and keeping those of digit size. Those were clustered by
NCC at a 0.82 threshold into 62 groups; the 24 largest (89% of the bank) were labelled by eye
off a contact sheet, every glyph was assigned to its nearest labelled cluster, and the ones
scoring above 0.80 were averaged per digit. Per-digit sample counts were::

    0:432  1:160  2:48  3:26  4:74  5:41  6:123  7:55  8:127  9:77

Uneven because HP values are uneven -- `0` is over-represented by every round number in the game
and `3` is the rarest at 26. That imbalance costs nothing here: these are class MEANS, not a
fitted decision boundary, so a digit with 26 samples is as sharp as one with 432.

**Confusability, measured rather than assumed.** NCC between the mean templates, worst pairs::

    6 vs 8  0.801      2 vs 7  0.791      3 vs 5  0.776      2 vs 3  0.771
    1 vs 3  0.738      5 vs 9  0.736      3 vs 7  0.730      8 vs 9  0.720

Nothing above 0.81, against a within-class assignment score whose median is 0.949. That gap is
why the `margin` this module returns -- best score minus runner-up -- is a usable confidence
signal and not noise: a real glyph beats its nearest rival by ~0.15, and a fragment of one does
not.
"""
from dataclasses import dataclass
from pathlib import Path

import cv2
import numpy as np

# Canonical glyph canvas. 18x14 is not arbitrary: digits measure 15-17 px tall and 4-16 px wide in
# the normalized frame, so this upsamples slightly rather than throwing detail away, and the
# canvas is WIDER than the widest glyph so nothing is clipped. Height is filled and width is
# centred, which keeps ASPECT as a feature -- `1` is half the width of `0`, and squashing every
# glyph to a square would discard the single cheapest cue separating them.
GLYPH_H = 18
GLYPH_W = 14

DATA_DIR = Path(__file__).resolve().parent / "data"
TEMPLATES_PATH = DATA_DIR / "digits.npz"


@dataclass(frozen=True)
class Glyph:
    """One classified digit. `score` is the NCC against the winning template, `margin` is how far
    it beat the runner-up -- and the two say different things. A blurred `8` still correlates 0.9
    with the `8` template (high score) while sitting 0.02 from `6` (low margin); a fragment of a
    digit occluded by a damage popup correlates badly with everything (low score) but can happen
    to beat second place comfortably (high margin). Both are reported because either alone lets a
    different failure through."""
    digit: int
    score: float
    margin: float
    xyxy: tuple[int, int, int, int]


def normalize(mask: np.ndarray) -> np.ndarray:
    """A binary glyph mask -> the canonical `GLYPH_H x GLYPH_W` float canvas.

    Resized to fill the HEIGHT and centred in width. Height rather than width because the font is
    proportional -- every digit shares a cap height, and none share a width.
    """
    h, w = mask.shape[:2]
    if h < 1 or w < 1:
        return np.zeros((GLYPH_H, GLYPH_W), np.float32)
    # INTER_AREA, matching `detector._letterbox`: these masks are downsampled as often as up, and
    # point-sampling a 4 px-wide stroke is how a `1` starts looking like noise.
    new_w = max(1, min(GLYPH_W, int(round(w * GLYPH_H / h))))
    small = cv2.resize(mask.astype(np.float32), (new_w, GLYPH_H), interpolation=cv2.INTER_AREA)
    canvas = np.zeros((GLYPH_H, GLYPH_W), np.float32)
    x0 = (GLYPH_W - new_w) // 2
    canvas[:, x0:x0 + new_w] = small
    return canvas


def _whiten(rows: np.ndarray) -> np.ndarray:
    """Mean-subtract and L2-normalize each row, so a dot product IS the correlation coefficient."""
    flat = rows.reshape(len(rows), -1).astype(np.float64)
    flat = flat - flat.mean(1, keepdims=True)
    return flat / (np.linalg.norm(flat, axis=1, keepdims=True) + 1e-9)


class GlyphBank:
    """The ten templates, loaded once and reused. Construct via `GlyphBank.load()`.

    Holds the whitened templates rather than re-normalizing per call: classification is then one
    (10, 252) @ (252,) matrix-vector product per digit, which is why the whole reader costs far
    less than the detector that feeds it.
    """

    def __init__(self, templates: np.ndarray, meta: dict | None = None):
        if templates.shape != (10, GLYPH_H, GLYPH_W):
            raise ValueError(
                f"expected 10 templates of {GLYPH_H}x{GLYPH_W}, got {templates.shape}. The file "
                f"is regenerated by scripts/vision_hp_calibrate.py, not edited."
            )
        self.templates = templates.astype(np.float32)
        self.meta = meta or {}
        self._whitened = _whiten(self.templates)

    @classmethod
    def load(cls, path: str | Path | None = None) -> "GlyphBank":
        path = Path(path) if path is not None else TEMPLATES_PATH
        if not path.exists():
            raise FileNotFoundError(
                f"digit templates are missing: {path}\n"
                f"They are a measured artifact, regenerated with:\n"
                f"    python scripts/vision_hp_calibrate.py <clip.mp4>"
            )
        with np.load(path, allow_pickle=False) as z:
            templates = z["templates"].astype(np.float32) / 255.0
            meta = {k: z[k].tolist() for k in z.files if k != "templates"}
        return cls(templates, meta)

    def classify(self, canvas: np.ndarray) -> tuple[int, float, float]:
        """A canonical glyph canvas -> `(digit, score, margin)`."""
        f = canvas.reshape(-1).astype(np.float64)
        f = f - f.mean()
        f /= np.linalg.norm(f) + 1e-9
        sims = self._whitened @ f
        order = np.argsort(-sims)
        return int(order[0]), float(sims[order[0]]), float(sims[order[0]] - sims[order[1]])


def save(templates: np.ndarray, path: str | Path | None = None, **meta) -> Path:
    """Write a template set. Used by the calibration script; stored as uint8 because these are
    class means of binary masks and the extra precision of float32 would be recording noise."""
    path = Path(path) if path is not None else TEMPLATES_PATH
    path.parent.mkdir(parents=True, exist_ok=True)
    quantized = np.clip(templates * 255.0, 0, 255).astype(np.uint8)
    np.savez_compressed(path, templates=quantized,
                        **{k: np.asarray(v) for k, v in meta.items()})
    return path
