"""Regenerates docs/OBSERVATION.md from brawl_sim.core.obs_schema.OBS_SCHEMA, and (Step 32)
docs/AGENT_OBS.md from configs/agent_obs.yaml via core.obs_select. Run after any change to
core/observation.py's field set or configs/agent_obs.yaml -- Step 26's acceptance criterion is
that every build_obs field appears in OBS_SCHEMA and vice versa, and this script's whole job is
to make the checked-in docs a faithful, regeneratable render of those sources of truth. Never
hand-edit docs/OBSERVATION.md or docs/AGENT_OBS.md; edit OBS_SCHEMA / agent_obs.yaml and rerun
this instead.
"""
import sys
from pathlib import Path

from brawl_sim.config import load_config
from brawl_sim.core import obs_select
from brawl_sim.core.obs_schema import OBS_SCHEMA

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS_PATH = REPO_ROOT / "docs" / "OBSERVATION.md"
AGENT_DOCS_PATH = REPO_ROOT / "docs" / "AGENT_OBS.md"
AGENT_OBS_YAML = REPO_ROOT / "configs" / "agent_obs.yaml"
DEFAULT_YAML = REPO_ROOT / "configs" / "default.yaml"

# Top-level group order -- matches core/observation.py's own dict-construction order.
_GROUP_ORDER = (
    "hero", "entities", "projectiles", "boxes", "pickups", "zone", "visibility",
    "view", "world", "action_mask", "meta",
)


def _group_of(dotted_name: str) -> str:
    return dotted_name.split(".", 1)[0]


def _fmt_bound(x, is_low: bool) -> str:
    if x is None:
        return "-inf" if is_low else "inf"
    return str(x)


def render() -> str:
    lines = [
        "# Observation package",
        "",
        "Generated by `scripts/dump_obs_schema.py` from `brawl_sim.core.obs_schema.OBS_SCHEMA` "
        "-- do not hand-edit. Shapes use symbolic dims: `N` = n_envs, `E` = 1 + n_enemies, "
        "`P` = max_projectiles, `B` = max_boxes, `U` = max_pickups, `H`/`W` = map_h/map_w, "
        "`VH`/`VW` = view_h/view_w, `MOVE` = n_move_bins + 1. See `obs_spec(cfg)` to resolve "
        "these against a real config.",
        "",
    ]

    for group in _GROUP_ORDER:
        # dict preserves insertion order (Python 3.7+), and OBS_SCHEMA was built from a single
        # fixed-order tuple, so this filter is a stable, deterministic sub-sequence every run.
        rows = [(name, spec) for name, spec in OBS_SCHEMA.items() if _group_of(name) == group]
        if not rows:
            continue

        lines.append(f"## `{group}`")
        lines.append("")
        lines.append("| field | shape | dtype | units | range | privileged | description |")
        lines.append("|---|---|---|---|---|---|---|")
        for name, spec in rows:
            shape_str = "(" + ", ".join(str(d) for d in spec.shape) + ("," if len(spec.shape) == 1 else "") + ")"
            range_str = (
                f"[{_fmt_bound(spec.range[0], True)}, {_fmt_bound(spec.range[1], False)}]"
                if spec.range is not None else "-"
            )
            priv_str = "yes" if spec.privileged else ""
            cond_str = f" (only when `cfg.{spec.conditional}`)" if spec.conditional else ""
            lines.append(
                f"| `{name}` | {shape_str} | {spec.dtype} | {spec.units} | {range_str} | "
                f"{priv_str} | {spec.description}{cond_str} |"
            )
        lines.append("")

    return "\n".join(lines)


def render_agent_obs() -> str:
    """Renders docs/AGENT_OBS.md from configs/agent_obs.yaml, resolved against the plain
    `configs/default.yaml` (no overrides) -- the same "one reference cfg, no env-specific
    overrides" convention `render()` above uses for docs/OBSERVATION.md."""
    cfg = load_config(str(DEFAULT_YAML))
    spec = obs_select.load_agent_spec(str(AGENT_OBS_YAML), cfg)
    index_map = obs_select.agent_obs_index_map(spec, cfg)

    lines = [
        "# Agent observation space",
        "",
        "Generated by `scripts/dump_obs_schema.py` from `configs/agent_obs.yaml` (resolved "
        "against `configs/default.yaml`) via `brawl_sim.core.obs_select` -- do not hand-edit. "
        f"`fair: {spec.fair}`, `normalize: {spec.normalize}`. Each group below is one top-level "
        "key of the flat `gymnasium.spaces.Dict` `agent_space(spec, cfg)` returns.",
        "",
    ]

    for g in spec.groups:
        lines.append(f"## `{g.name}`")
        lines.append("")
        lines.append(f"shape: `{g.shape}`, dtype: `{g.dtype}`" + (", per_entity" if g.per_entity else ""))
        if g.max_slots is not None:
            lines.append(
                f"\n**Not index-stable** -- the {g.max_slots} nearest (by "
                f"`{g.entity_prefix}.time_to_closest`) live slots, re-selected every tick; "
                "zero-padded when fewer than that many are alive."
            )
        lines.append("")
        if g.view_channels is not None:
            lines.append("| channel index | source `view` channel |")
            lines.append("|---|---|")
            for i, ch in enumerate(g.view_channels):
                lines.append(f"| {i} | `{ch}` |")
        else:
            lines.append("| columns | field | source units |")
            lines.append("|---|---|---|")
            for f in g.fields:
                start, end = index_map[g.name][f]
                units = OBS_SCHEMA[f].units
                lines.append(f"| [{start}, {end}) | `{f}` | {units} |")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    DOCS_PATH.parent.mkdir(parents=True, exist_ok=True)
    DOCS_PATH.write_text(render(), encoding="utf-8")
    print(f"wrote {DOCS_PATH}")

    AGENT_DOCS_PATH.write_text(render_agent_obs(), encoding="utf-8")
    print(f"wrote {AGENT_DOCS_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
